spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btl_android?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12112001
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: none